import Head from 'next/head'
import React from 'react'
import Navbar from '../Navbar'

const Layout = ({ title , children}) => {
  return (
    <>
    <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800&display=swap" rel="stylesheet"></link>
      </Head>
      <Navbar />
      {children}
    </>
  )
}

export default Layout