import Head from 'next/head'
import styled, { ThemeProvider } from 'styled-components'
import { GlobalStyles } from '../styles/Global'
import { theme } from '../styles/theme'

export default function Home() {
  return (
    <>
      <Head>
        <title>breakOut University</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800&display=swap" rel="stylesheet"></link>
      </Head>
      <ThemeProvider theme={theme}>
        <GlobalStyles />
      </ThemeProvider>
    </>
  )
}
